export const SAVE_NEW_JOB = "SAVE_NEW_JOB";
export const GET_SAVED_JOBS = "GET_SAVED_JOBS";
export const GET_SAVED_JOBS_FAILURE = "GET_SAVED_JOBS_FAILURE";
export const REMOVE_JOB = "REMOVE_JOB";

export const GET_USER_FAILURE = "GET_USER_FAILURE";
export const GET_USER_INFO = "GET_USER_INFO";
